# core_ai/keystroke_ai.py
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # Mutes TensorFlow C++ hardware warnings

import numpy as np
import math
import joblib
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
tf.get_logger().setLevel('ERROR')         # Mutes TensorFlow Python deprecation warnings
from tensorflow import keras # type: ignore
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout

class CadenceKeystrokeEngine:
    def __init__(self, model_dir="database/models"):
        self.model_dir = model_dir
        os.makedirs(self.model_dir, exist_ok=True)
        
        # Dual Engine Design (TensorFlow + Scikit-Learn)
        self.svm_model = OneClassSVM(kernel='rbf', gamma='scale', nu=0.1)
        self.scaler = StandardScaler()
        self.lstm_model = self._build_lstm_model()
        
        self.svm_path = os.path.join(self.model_dir, "keystroke_svm.pkl")
        self.scaler_path = os.path.join(self.model_dir, "keystroke_scaler.pkl")
        self.lstm_path = os.path.join(self.model_dir, "keystroke_lstm.keras")
        
        self.is_quick_trained = False
        self.is_deep_trained = False
        
        self._load_models()

    def _build_lstm_model(self):
        # Input shape updated to (None, 1) to dynamically accept the 1D flight-time arrays
        model = Sequential([
            LSTM(64, input_shape=(None, 1), return_sequences=True),
            Dropout(0.2),
            LSTM(32),
            Dense(16, activation='relu'),
            Dense(1, activation='sigmoid')
        ])
        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
        return model

    def _load_models(self):
        if os.path.exists(self.svm_path) and os.path.exists(self.scaler_path):
            self.svm_model = joblib.load(self.svm_path)
            self.scaler = joblib.load(self.scaler_path)
            self.is_quick_trained = True
            
        if os.path.exists(self.lstm_path):
            self.lstm_model = keras.models.load_model(self.lstm_path)
            self.is_deep_trained = True

    def train_quick_setup(self, dwell_flight_data):
        if len(dwell_flight_data) == 0:
            return False
            
        # FIX: Normalize the raw millisecond timings to prevent Euclidean distortion
        scaled_data = self.scaler.fit_transform(dwell_flight_data)
            
        self.svm_model.fit(scaled_data)
        joblib.dump(self.svm_model, self.svm_path)
        joblib.dump(self.scaler, self.scaler_path)
        self.is_quick_trained = True
        return True

    def verify_quick_setup(self, sequence):
        if not self.is_quick_trained:
            raise ValueError("Quick setup model is not trained yet.")
            
        sequence = np.array(sequence)
        # Ensure 2D formatting for SVM: (samples, features)
        if len(sequence.shape) == 1:
            sequence = sequence.reshape(1, -1)
            
        # Standardize the incoming login attempt
        scaled_seq = self.scaler.transform(sequence)
            
        # FIX: Calculate exact distance from hyperplane instead of basic 1 or -1
        distance = self.svm_model.decision_function(scaled_seq)[0]
        
        # Apply Sigmoid function to convert raw distance into a 0.0 - 1.0 confidence score
        # A distance of 0 (exactly on the boundary) becomes a score of 0.5 (50%)
        score = 1 / (1 + math.exp(-distance))
        
        # Any score above 50% means the point is inside the normal boundary
        success = score > 0.50
        
        return success, score 

    def train_deep_learning(self, sequences, labels, epochs=15):
        # Force execution on CPU
        with tf.device('/CPU:0'):
            sequences = np.array(sequences)
            
            # Dimension fix: Reshape (Batch, Steps) into (Batch, Steps, Features=1)
            if len(sequences.shape) == 2:
                sequences = np.expand_dims(sequences, axis=-1) 
            # Batch size set to 1 to handle the small sample arrays generated by the UI
            self.lstm_model.fit(sequences, labels, epochs=epochs, batch_size=1, verbose=1)
            
        self.lstm_model.save(self.lstm_path)
        self.is_deep_trained = True
        return True

    def verify_deep_learning(self, sequence):
        if not self.is_deep_trained:
            raise ValueError("Deep learning model is not trained yet.")
            
        with tf.device('/CPU:0'):
            sequence = np.array(sequence)
            
            # Dimension fix: Reshape 1D incoming login attempt to (1, Steps, 1)
            if len(sequence.shape) == 1:
                sequence = sequence.reshape(1, -1, 1)
            elif len(sequence.shape) == 2:
                sequence = np.expand_dims(sequence, axis=-1)
            prediction = self.lstm_model.predict(sequence, verbose=0)
        score = float(prediction[0][0])
        success = score > 0.85
        return success, score